### ISSUE TITLE
Recommend Alconna

### ISSUE THREAD

**Issue by RF-Tar-Railt** [shenjackyuanjie/lib-not-dr#2]
我在翻阅 [NEPattern](https://github.com/ArcletProject/NEPattern) 的依赖网络时发现了您的仓库，遂向您推销一下同一个项目下的命令行工具库 [Alconna](https://github.com/ArcletProject/Alconna)

**Comment by shenjackyuanjie** [comment]
啊哈！
非常感谢，不过这个仓库的目标是不带任何额外依赖 并且也不止专注于命令行工具库
可以参考 [mcdr](https://github.com/Fallen-Breath/MCDReforged) 的开发文档里面的命令解析
非常感谢~
